package Vistas;

import Controlador.Controlador;
import Modelo.*;
import java.util.*;
import javax.swing.*;

public class MenuLaboreosDeUnCultivo extends javax.swing.JFrame {

    private Controlador controlador;
    private Cultivo cultivoSeleccionado;
    private List<Laboreo> listLaboreo;
    private List<JComboBox> cbsLaboreos = new ArrayList<>();
    
    public MenuLaboreosDeUnCultivo(Controlador controlador, Cultivo cultivoSeleccionado) {
        this.initComponents();
        listLaboreo = new ArrayList<>();
        this.cbsLaboreos.add(cbLaboreo1);
        this.cbsLaboreos.add(cbLaboreo2);
        this.cbsLaboreos.add(cbLaboreo3);
        this.cbsLaboreos.add(cbLaboreo4);
        this.cbsLaboreos.add(cbLaboreo5);
        this.cbsLaboreos.add(cbLaboreo6);
        this.cbsLaboreos.add(cbLaboreo7);
        this.cbsLaboreos.add(cbLaboreo8);
        this.controlador = controlador;
        this.cultivoSeleccionado = cultivoSeleccionado;
        if(this.cultivoSeleccionado.tieneProyectosActivos()) {
            this.btnGuardar.setEnabled(false);
        }
        this.txtNumero.setText(String.valueOf(cultivoSeleccionado.getIdcultivo()));
        this.txtNombre.setText(cultivoSeleccionado.getNombre());
        iniciarCombosBox();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDatosCultivo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLaboreos = new javax.swing.JLabel();
        cbLaboreo1 = new javax.swing.JComboBox<>();
        cbLaboreo2 = new javax.swing.JComboBox<>();
        lblLaboreo1 = new javax.swing.JLabel();
        lblLaboreo2 = new javax.swing.JLabel();
        lblLaboreo3 = new javax.swing.JLabel();
        cbLaboreo3 = new javax.swing.JComboBox<>();
        lblLaboreo4 = new javax.swing.JLabel();
        cbLaboreo4 = new javax.swing.JComboBox<>();
        lblLaboreo5 = new javax.swing.JLabel();
        cbLaboreo5 = new javax.swing.JComboBox<>();
        lblLaboreo6 = new javax.swing.JLabel();
        cbLaboreo6 = new javax.swing.JComboBox<>();
        lblLaboreo7 = new javax.swing.JLabel();
        cbLaboreo7 = new javax.swing.JComboBox<>();
        lblLaboreo8 = new javax.swing.JLabel();
        cbLaboreo8 = new javax.swing.JComboBox<>();
        btnAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ver Laboreos de un Cultivo");
        setResizable(false);

        txtNumero.setEditable(false);

        lblNumero.setText("Número:");

        txtNombre.setEditable(false);

        lblNombre.setText("Nombre:");

        jPanel2.setLayout(new java.awt.BorderLayout());

        lblDatosCultivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatosCultivo.setText("Datos del Cultivo");
        lblDatosCultivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblDatosCultivo, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        lblLaboreos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLaboreos.setText("Laboreos del Cultivo");
        jPanel3.add(lblLaboreos, java.awt.BorderLayout.CENTER);

        cbLaboreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaboreo1ActionPerformed(evt);
            }
        });

        cbLaboreo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaboreo2ActionPerformed(evt);
            }
        });

        lblLaboreo1.setText("Laboreo de Orden #1:");

        lblLaboreo2.setText("Laboreo de Orden #2:");

        lblLaboreo3.setText("Laboreo de Orden #3:");

        cbLaboreo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaboreo3ActionPerformed(evt);
            }
        });

        lblLaboreo4.setText("Laboreo de Orden #4:");

        cbLaboreo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaboreo4ActionPerformed(evt);
            }
        });

        lblLaboreo5.setText("Laboreo de Orden #5:");

        cbLaboreo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaboreo5ActionPerformed(evt);
            }
        });

        lblLaboreo6.setText("Laboreo de Orden #6:");

        cbLaboreo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaboreo6ActionPerformed(evt);
            }
        });

        lblLaboreo7.setText("Laboreo de Orden #7:");

        cbLaboreo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaboreo7ActionPerformed(evt);
            }
        });

        lblLaboreo8.setText("Laboreo de Orden #8:");

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(txtNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblLaboreo1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(lblLaboreo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLaboreo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLaboreo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblLaboreo8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLaboreo7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLaboreo6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLaboreo5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLaboreo8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLaboreo7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLaboreo6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLaboreo5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLaboreo4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLaboreo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLaboreo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLaboreo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtras)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumero)
                    .addComponent(lblNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLaboreo1)
                    .addComponent(lblLaboreo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLaboreo2)
                    .addComponent(lblLaboreo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLaboreo3)
                    .addComponent(lblLaboreo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLaboreo4)
                    .addComponent(lblLaboreo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLaboreo5)
                    .addComponent(lblLaboreo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLaboreo6)
                    .addComponent(lblLaboreo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLaboreo7)
                    .addComponent(lblLaboreo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLaboreo8)
                    .addComponent(lblLaboreo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAviso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAtras)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
        MenuCultivo mc = new MenuCultivo(controlador);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cbLaboreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaboreo1ActionPerformed
        if(cbLaboreo1.getSelectedIndex() == 0) {
            try {
                cbLaboreo2.setSelectedIndex(0);
            } catch(Exception e) {}
            cbLaboreo2.setEnabled(false);
        } else {
            cbLaboreo2.setEnabled(true);
        }
    }//GEN-LAST:event_cbLaboreo1ActionPerformed

    private void cbLaboreo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaboreo2ActionPerformed
        if(cbLaboreo2.getSelectedIndex() == 0) {
            try {
                cbLaboreo3.setSelectedIndex(0);
            } catch(Exception e) {}
            cbLaboreo3.setEnabled(false);
        } else {
            cbLaboreo3.setEnabled(true);
        }
    }//GEN-LAST:event_cbLaboreo2ActionPerformed

    private void cbLaboreo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaboreo3ActionPerformed
        if(cbLaboreo3.getSelectedIndex() == 0) {
            try {
                cbLaboreo4.setSelectedIndex(0);
            } catch(Exception e) {}
            cbLaboreo4.setEnabled(false);
        } else {
            cbLaboreo4.setEnabled(true);
        }
    }//GEN-LAST:event_cbLaboreo3ActionPerformed

    private void cbLaboreo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaboreo4ActionPerformed
        if(cbLaboreo4.getSelectedIndex() == 0) {
            try {
                cbLaboreo5.setSelectedIndex(0);
            } catch(Exception e) {}
            cbLaboreo5.setEnabled(false);
        } else {
            cbLaboreo5.setEnabled(true);
        }
    }//GEN-LAST:event_cbLaboreo4ActionPerformed

    private void cbLaboreo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaboreo5ActionPerformed
        if(cbLaboreo5.getSelectedIndex() == 0) {
            try {
                cbLaboreo6.setSelectedIndex(0);
            } catch(Exception e) {}
            cbLaboreo6.setEnabled(false);
        } else {
            cbLaboreo6.setEnabled(true);
        }
    }//GEN-LAST:event_cbLaboreo5ActionPerformed

    private void cbLaboreo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaboreo6ActionPerformed
        if(cbLaboreo6.getSelectedIndex() == 0) {
            try {
                cbLaboreo7.setSelectedIndex(0);
            } catch(Exception e) {}
            cbLaboreo7.setEnabled(false);
        } else {
            cbLaboreo7.setEnabled(true);
        }
    }//GEN-LAST:event_cbLaboreo6ActionPerformed

    private void cbLaboreo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaboreo7ActionPerformed
        if(cbLaboreo7.getSelectedIndex() == 0) {
            try {
                cbLaboreo8.setSelectedIndex(0);
            } catch(Exception e) {}
            cbLaboreo8.setEnabled(false);
        } else {
            cbLaboreo8.setEnabled(true);
        }
    }//GEN-LAST:event_cbLaboreo7ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Si no se eligió ningun laboreo, osea el primer laboreo es "NIGNUNO"
        if(cbLaboreo1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "El cultivo debe tener al menos un laboreo.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Se borran todos los Cultivoxlaboreo que existan de este cultivo
            for(Cultivoxlaboreo cxl: cultivoSeleccionado.getCultivoxlaboreos()) {
                this.controlador.borrarObjeto(cxl);
            }
            Iterator<Cultivoxlaboreo> iter = cultivoSeleccionado.getCultivoxlaboreos().iterator();
            while(iter.hasNext()) {
                Cultivoxlaboreo nextCxl = iter.next();
                iter.remove();
            }
            // Se pregunta que opcion se eligio en cada combobox
            for(int i = 0; i < cbsLaboreos.size(); i++) {
                // Si es "NIGUNO", el resto tambíen son "NINGUNO", entonces se rompe el bucle
                if(cbsLaboreos.get(i).getSelectedIndex() == 0) {
                    break;
                // Si no es "NIGUNO", se crea el Cultivoxlaboreo correspondiente y se lo agrega a la DB
                } else {
                    Cultivoxlaboreo nuevoCxl = new Cultivoxlaboreo(cultivoSeleccionado, listLaboreo.get(cbsLaboreos.get(i).getSelectedIndex() - 1), i + 1);
                    cultivoSeleccionado.getCultivoxlaboreos().add(nuevoCxl);
                    this.controlador.agregarObjeto(nuevoCxl);
                }
            }
            this.controlador.actualizarObjeto(cultivoSeleccionado);
            this.lblAviso.setText("Laboreos actualizados.");
            iniciarCombosBox();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private void iniciarCombosBox() {
        // Se cargan las opciones de todos los combo box
        this.listLaboreo = this.controlador.getLaboreos();
        for(JComboBox cb: this.cbsLaboreos) {
            cb.removeAllItems();
            cb.addItem("NINGUNO");
            for(Laboreo l: this.listLaboreo) {
                cb.addItem(l.getNombre());
            }
        }
        // Se preselecciona la opcion que corresponda
        List<Cultivoxlaboreo> laboreosDelCultivo = new ArrayList<>(cultivoSeleccionado.getCultivoxlaboreos());
        for(int i = 0; i < laboreosDelCultivo.size(); i++) {
            cbsLaboreos.get(laboreosDelCultivo.get(i).getOrden() - 1).setSelectedIndex(laboreosDelCultivo.get(i).getLaboreo().getIdlaboreo());
        }
        // Se deshabilitan los combo box que correspondan
        /*for(int i = 0; i < cbsLaboreos.size() - 1; i++) {
            if(cbsLaboreos.get(i).getSelectedIndex() == 0) {
                cbsLaboreos.get(i + 1).setEnabled(false);
            }
        }*/
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbLaboreo1;
    private javax.swing.JComboBox<String> cbLaboreo2;
    private javax.swing.JComboBox<String> cbLaboreo3;
    private javax.swing.JComboBox<String> cbLaboreo4;
    private javax.swing.JComboBox<String> cbLaboreo5;
    private javax.swing.JComboBox<String> cbLaboreo6;
    private javax.swing.JComboBox<String> cbLaboreo7;
    private javax.swing.JComboBox<String> cbLaboreo8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblDatosCultivo;
    private javax.swing.JLabel lblLaboreo1;
    private javax.swing.JLabel lblLaboreo2;
    private javax.swing.JLabel lblLaboreo3;
    private javax.swing.JLabel lblLaboreo4;
    private javax.swing.JLabel lblLaboreo5;
    private javax.swing.JLabel lblLaboreo6;
    private javax.swing.JLabel lblLaboreo7;
    private javax.swing.JLabel lblLaboreo8;
    private javax.swing.JLabel lblLaboreos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
